### ISSUE TITLE
Missing parameter in catalystcenter_transit_peer_network

### ISSUE THREAD

**Issue by jolstorn** [CiscoDevNet/terraform-provider-catalystcenter#121]
Resource and data source catalystcenter_transit_peer_network is missing attribute `isMulticastOverTransitEnabled`.

[Catalyst Center API reference for 2.3.7](]https://developer.cisco.com/docs/dna-center/add-transit-networks/) describe

```
Settings required for the transit network of type SDA_LISP_PUB_SUB_TRANSIT or SDA_LISP_BGP_TRANSIT.
    isMulticastOverTransitEnabled:boolean
    Set this to true to enable multicast over SD-Access transit. This supports Native Multicast over SD-Access Transit. This is only applicable for transit of type SDA_LISP_PUB_SUB_TRANSIT.
```
This attribute is not reflected in the provider and I assume it's set default false?

I would also appreciate if the provider followed API attributes, like using controlPlaneNetworkDeviceIds (API) instead of device_management_ip_address + site_name_hierarichy, although this is subordinate.

**Comment by kuba-mazurkiewicz** [comment]
this resource is still using old API: dna/intent/api/v1/business/sda/transit-peer-network,

new API: dna/intent/api/v1/sda/transitNetworks with this multicast field will be done in next release:

https://github.com/CiscoDevNet/terraform-provider-catalystcenter/pull/119

**Comment by jolstorn** [comment]
Ok. Thank you. I will close this issue.
