### ISSUE TITLE
Import of catalystcenter_ip_pool_reservation failes due to missing site_id

### ISSUE THREAD

**Issue by jolstorn** [CiscoDevNet/terraform-provider-catalystcenter#70]
Import of resources to catalystcenter_ip_pool_reservation failes with 
```
Error: Client Error
│ 
│ Failed to retrieve object (GET), got error: HTTP Request failed: StatusCode 400, {"status":false,"message":["Either siteId or ignoreInheritedGroups need to be passed."]}
```
Using config-driven import with 
```
import {
  for_each  = var.reserved_pools
   id       = dnacenter_reserve_ip_subpool.this[each.value.name].item[0].id
   to       = catalystcenter_ip_pool_reservation.pool_reserved[each.value.name]
}
```

**Comment by danischm** [comment]
Indeed, the GET request requires the site ID which is currently not available when importing the resource. We would need to encode the site ID into the "import ID" to support this.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-catalystcenter/commit/9f38910bdfd6cbd5058cdb765862c38ef4de36cd

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-catalystcenter/commit/9a3f2d430a64b1eacd245235787d56c4f7702d32

**Comment by danischm** [comment]
Please let me know if this fixes your issue. Thanks!

**Comment by kuba-mazurkiewicz** [comment]
hey @danischm 
I checked both terraform import command and config driven import and they both work with latest provider version

**Comment by danischm** [comment]
Excellent!

**Comment by jolstorn** [comment]
I tested this as well now and config-driven import works with our code without issues. Thank you!
