### ISSUE TITLE
incorrect required parameters in resource catalystcenter_transit_peer_network

### ISSUE THREAD

**Issue by jolstorn** [CiscoDevNet/terraform-provider-catalystcenter#92]
`autonomous_system_number` and `routing_protocol_name` are only required when `transit_peer_network_type` is `ip_transit`.

https://github.com/CiscoDevNet/terraform-provider-catalystcenter/blob/534b336f3c0ed5f097ffa39474cef96c2e79dec0/internal/provider/data_source_catalystcenter_transit_peer_network.go#L74-L81

When `transit_peer_network_type` is `sda_transit_with_lisp_bgp` or `sda_transit_with_pub_sub`, these parameters should not be present.

Vice versa when type is `ip_transit`, `sda_transit_settings` should not be present.

This is according to CC [API Documentation](https://developer.cisco.com/docs/dna-center/add-transit-peer-network/)

**Comment by danischm** [comment]
Fixed here: https://github.com/CiscoDevNet/terraform-provider-catalystcenter/commit/b0f3f477a4ce102e3d732588bc864be31cbd42ea

**Comment by danischm** [comment]
Added in v0.1.10 release.
